# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Pegasus\PegasusOrderApiClient:
        arguments:
            $apiBase: '%env(string:PEGASUS_API_BASE)%'
            $apiUser: '%env(string:PEGASUS_API_USER)%'
            $apiSecret: '%env(string:PEGASUS_API_SECRET)%'
            $createOrderPath: '%env(string:PEGASUS_CREATE_ORDER_PATH)%'
            $itemSku: '%env(string:PEGASUS_ITEM_SKU)%'
            $itemEan: '%env(string:PEGASUS_ITEM_EAN)%'

    App\Middleware\MiddlewareProductRepository:
        arguments:
            $host: '%env(string:PEGASUS_STAGING_DB_IP)%'
            $user: '%env(string:PEGASUS_STAGING_DB_USER)%'
            $password: '%env(string:PEGASUS_STAGING_DB_PASSWORD)%'
            $schema: '%env(string:PEGASUS_STAGING_DB_SCHEMA)%'
            $port: '%env(int:PEGASUS_STAGING_DB_PORT)%'

    app.repo.api_user.staging:
        class: App\Middleware\ApiUserRepository
        arguments:
            $host: '%env(string:PEGASUS_STAGING_DB_IP)%'
            $user: '%env(string:PEGASUS_STAGING_DB_USER)%'
            $password: '%env(string:PEGASUS_STAGING_DB_PASSWORD)%'
            $schema: '%env(string:PEGASUS_STAGING_DB_SCHEMA)%'
            $port: '%env(int:PEGASUS_STAGING_DB_PORT)%'

    app.repo.api_user.live:
        class: App\Middleware\ApiUserRepository
        arguments:
            $host: '%env(string:PEGASUS_LIVE_DB_IP)%'
            $user: '%env(string:PEGASUS_LIVE_DB_USER)%'
            $password: '%env(string:PEGASUS_LIVE_DB_PASSWORD)%'
            $schema: '%env(string:PEGASUS_LIVE_DB_SCHEMA)%'
            $port: '%env(int:PEGASUS_LIVE_DB_PORT)%'

    app.repo.duplicate.staging:
        class: App\Middleware\DuplicateUserRepository
        arguments:
            $host: '%env(string:PEGASUS_STAGING_DB_IP)%'
            $user: '%env(string:PEGASUS_STAGING_DB_USER)%'
            $password: '%env(string:PEGASUS_STAGING_DB_PASSWORD)%'
            $schema: '%env(string:PEGASUS_STAGING_DB_SCHEMA)%'
            $port: '%env(int:PEGASUS_STAGING_DB_PORT)%'

    app.repo.duplicate.live:
        class: App\Middleware\DuplicateUserRepository
        arguments:
            $host: '%env(string:PEGASUS_LIVE_DB_IP)%'
            $user: '%env(string:PEGASUS_LIVE_DB_USER)%'
            $password: '%env(string:PEGASUS_LIVE_DB_PASSWORD)%'
            $schema: '%env(string:PEGASUS_LIVE_DB_SCHEMA)%'
            $port: '%env(int:PEGASUS_LIVE_DB_PORT)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
